### ISSUE TITLE
32bit Addresses

### ISSUE THREAD

**Issue by wrenger** [gz/rust-multiboot#21]
From the `PAddr` type, I originally assumed that this crate only works on 64bit. But it also seems to work in my 32bit OS if the pointers are cast correctly.
So maybe it would be a good idea to change the numeric pointer types to `usize` instead of `u64` as using 64bit values on 32bit architectures is costly. 

PS: I don't know if `size_of::<*const ()>() == size_of::<usize>()` is guaranteed on every architecture. In any case, a compile-time check may be helpful:
```rust
const _: () = assert!(size_of::<*const ()>() == size_of::<PAddr>());
```

**Comment by gz** [comment]
Hey, Yes it might be better for PAddr to be an `usize`. `usize` is [guaranteed to be "pointer-sized"](https://doc.rust-lang.org/std/primitive.usize.html) so the assertion above will always hold. 

But unfortunately, this guarantee is for virtual addresses only: x86 is strange, there is also [PAE](https://en.wikipedia.org/wiki/Physical_Address_Extension) which permits physical addresses larger than usize on 32-bits (hence the choice of u64 in multiboot). Though, I'm not quite sure how much of an issue PAE is on multiboot and it might not actually matter. If we're sure that this wouldn't affect anyone using multiboot *and* PAE at the same time we could definitely change it to `usize`.

**Comment by gz** [comment]
There is at least some mention of [PAE in the multiboot spec](https://www.gnu.org/software/grub/manual/multiboot/multiboot.html) which suggests it is relevant/supported:

> The field ‘framebuffer_addr’ contains framebuffer physical address. This field is 64-bit wide but bootloader should set it under 4 GiB if possible for compatibility with kernels which aren’t aware of PAE or AMD64.

**Comment by wrenger** [comment]
Well ok, I didn't think about PAE. 
If an u64 is converted to a pointer on a 32bit PAE system, are the remaining 32bit then lost?
Could this be a bigger problem?

**Comment by gz** [comment]
If you convert a u64 to a u32 the upper half is lost if you're just doing a "plain" cast (`foo as u32`) in rust. But rust has simple ways to detect this problem at runtime: for example you can use the `TryInto` traits to do the casts.

Note though that PAE does not mean that you will end up with pointers to de-reference that are bigger than 32bits, just that you might have physical memory addresses that are bigger than 32-bits. To access that memory it will still have to be mapped into a 32-bit address space. But it still matters in the OS, for example if you're managing and retrieving the physical memory regions on the machine or if you're writing device drivers that do DMA with physical addresses etc.

**Comment by wrenger** [comment]
Yes you are right. This works as long as the physical address is never stored in a 32bit value and translated only by the user defined `paddr_to_slice` (which has to support PAE in this case).

All in all, this is such a minor issue that I would keep the 64bit `PAddr` just in case (even if PAE probably isn't that relevant anymore).
