### ISSUE TITLE
Functionality missing for using this in bootloaders

### ISSUE THREAD

**Issue by YtvwlD** [gz/rust-multiboot#7]
I'm planning on writing a Multiboot compatible bootloader and stumbled across this crate.

It looks really nice, but it currently just has functionality to use it in a kernel for parsing the Multiboot information passed by the bootloader.
Would you be willing to merge changes adding the missing functionality (I'm mainly thinking about a new `Header` type and `Multiboot::empty` and setters for the various information) or am I better off creating a new crate for that?

**Comment by gz** [comment]
Fixed in #8, thanks!
